package by.bsuir.enums;

public enum ClientRequestType {
    AUTHORIZE_STUDENT,
    REGISTER_STUDENT,
    GET_SCHEDULE,
    REGISTER_STUDENT_TO_QUEUE,
    REMOVE_STUDENT_FROM_QUEUE,
    GET_STUDENT_INFO,
    EDIT_STUDENT_PROFILE,
    GET_QUEUE_INFO,
    GET_GROUP_QUEUE,
    BECOME_GROUP_ADMIN,
    GET_GROUP_SCHEDULES,
    CHANGE_SORT_TYPE,
    GET_REQUESTS,
    ACCEPT_REQUEST,
    DECLINE_REQUEST,
    EXIT
}
