package by.bsuir.enums;

public enum ClientRequestType {
    AUTHORIZE_STUDENT,
    REGISTER_STUDENT,
    GET_SCHEDULE,
    REGISTER_STUDENT_TO_QUEUE,
    REMOVE_STUDENT_FROM_QUEUE,
    GET_STUDENT_INFO,
    EDIT_STUDENT_PROFILE,
    EXIT
}
