package by.bsuir.enums;

public enum RegistrationState {
    OK,
    ERROR,
    EMPTY_FIELDS,
    INCORRECT_USERNAME_OR_PASSWORD,
    GROUP_NOT_EXISTS,
    USERNAME_EXISTS,
    PASSWORDS_NOT_MATCHES,
    FAILED_TO_REGISTER_STUDENT_INTO_PRE_QUEUE
}
